### ISSUE TITLE
Make 'rm -f *' during compilation optional

### ISSUE THREAD

**Issue by davidzwa** [darkmattercoder/qt-build#14]
We are considering using this image to build our debugging version of the app, but currently all compilation .o-objects are removed making the process really slow.

Is it possible to add a flag SKIP_REMOVE to not remove all objects in the volume and thus speed up builds for development purposes?

We can take care of removing the unused .o objects ourselves (make command) thus giving back control to the developer.

**Comment by darkmattercoder** [comment]
You are right. The developer should be in control of the build dir cleaning. Fix should reach master after successful pipeline process.

**Comment by davidzwa** [comment]
You deserve absolute praise for this!
