### ISSUE TITLE
Dockerhub page badge list broken

### ISSUE THREAD

**Issue by davidzwa** [darkmattercoder/qt-build#20]
https://hub.docker.com/r/darkmattercoder/qt-build/

The list of builds tags/version seems disrupted at Qt version 5.9 and lower.

**Comment by darkmattercoder** [comment]
Thank you for bringing this up. At first, the images are all available in the dockerhub registry, so it is simply a rendering issue.

Strange: dockerhub overview has the issue
![image](https://user-images.githubusercontent.com/2217280/80730282-ace6e100-8b09-11ea-99cc-bfa59cb0db2f.png)

Wheras at github, it is looking good:

file:///tmp/Screenshot_20200430_173631.png
![image](https://user-images.githubusercontent.com/2217280/80730372-cc7e0980-8b09-11ea-9083-f084fdc22384.png)

I have no idea how dockerhub is handling the graphics in the readme but it looks to me as if they do a kind of preprocessing which stops, once a temporarily unavailable image is found.

I triggered the build manually and hope that the push hooks that get executed will cause dockerhub to re-render the readme.....

**Comment by darkmattercoder** [comment]
seems to be fixed in the meantime.
