### ISSUE TITLE
Cannot link libQt5Core to builded file

### ISSUE THREAD

**Issue by ahbensalah** [darkmattercoder/qt-build#21]
Hello,
I am new to docker and i try to build a Qt project through the detailed usage. As an example, I coloned the test project "helloword" that you propose and i build it from the docker container.

`docker run -it -u $UID -v /root/qt-build/tests/helloworld/:/var/build darkmattercoder/qt-build:5.11.3 bash`
`cd /var/build/`
`qmake helloworld.pro`
`make`

However, when i try to run the builded file inside the container, 
`./helloworld`

I get a linking problem related to libQt5Core.so.5 library. Even if I add the path of the missed library in LD_LIBRARY_PATH, i obtain the same problem.

Do I miss something ? Could you help me please ?

**Comment by darkmattercoder** [comment]
Hi, sorry for the late answer.
When I execute your above code, I am perfectly able to run the hello world example.

Could you provide a full output from your terminal for your error?

**Comment by darkmattercoder** [comment]
Closing this for now, feel free to reopen, if you still experience problems.
