### ISSUE TITLE
Run make install

### ISSUE THREAD

**Issue by amolinap** [darkmattercoder/qt-build#22]
Hi,

How can I run make install?

Thanks!!!

**Comment by darkmattercoder** [comment]
At the moment I have not forseen to implement a direct make install call via the included build command. However, you can always fire your container up in command line mode and call make install from there. But please be aware, that the behaviour depends on howyour qmake project is configured to perform an installation. You have to make sure, that all directories are relative to your project path to make it succeed from within the container. Often you will have absolute paths, which most likely are not accessible from within the container.

As the project here is mainly targeting people who want to include a build in their ci/cd environment, the actual use of make install is something that I do not expect to happen very often. 

So I consider that issue out of scope for now.
