### ISSUE TITLE
Build image with qtwebengine

### ISSUE THREAD

**Issue by kluszon** [darkmattercoder/qt-build#28]
Hi,

I'm trying to build an image for Qt 5.15.2 with qtwebengine. I'm using your script **build-dockerfile-local.sh** and I removed `-skip qtwebengine` from **buildconfig/configure-5.15.2.sh**. I build it, but I don't have `webenginewidgets` in the image. What should I do?

As I understand I should use image **darkmattercoder/qt-build:5.15.2**, because **darkmattercoder/qt-build:builder-5.15.2** and **darkmattercoder/qt-build:base-5.15.2** are only images necessary for build process?

**Comment by darkmattercoder** [comment]
Hi @kluszon,

as I state in the description of the project, I am no longer maintaining it. So I cannot give extensive help. I would suggest looking at the configure log freom the configure step, whether there is something mentioned as missing. For example some requirements that are missing for QtWebengine?

I am sorry that I cannot help further.

**Comment by kluszon** [comment]
@darkmattercoder Thank you for your answer. I was hoping that some other user has experience in this area and can prompt something.
