### ISSUE TITLE
sql plugins

### ISSUE THREAD

**Issue by windymindy** [darkmattercoder/qt-build#4]
As the description says "A (nearly) full qt build environment", you might want to also build plugins from source. When installed from official web site Qt comes with a huge amount of plugins, sql drivers being one of them.
When building from source configure script checks whether a certain backend sql library is available to include a plugin to make file https://doc.qt.io/qt-5/sql-driver.html.

Let's say I want to build application which uses QtSql module and deploy it to run against mariadb. It won't depend on sqldrivers/qsqlmysql.so at build time. But if I am to run interation tests or to copy binaries for deployment I am going to require sqldrivers/qsqlmysql.so along with libmysqlclient.so.18.

Do you mind to prebuild those countless plugins like Qt does? Or should one use darkmattercoder/qt-build:builder-??? to build required plugins.

**Comment by darkmattercoder** [comment]
Thanks for your input, I now see the concerns. Let me think about it and I am sure, we can add that somehow.

**Comment by hmoffatt** [comment]
+1. For MySQL and Postgres you probably only need to install the relevant -dev packages in the base image and Qt will automatically find them and build the plugins.

I need the Interbase driver, so I modified the dockerfile to add firebird-dev, but I also had to patch one of the Qt source files because it looks for the wrong library name by default.

**Comment by hmoffatt** [comment]
I added libpq-dev and libmysqlclient-dev and those plugins built fine.

I'm not sure how to add a test for this though. It looks like the tests are only compiled (not run), and I don't think there's a way to check for a plug-in at compile time, other than just looking for it in the file system.
